-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:74d063254b00b4b4f0ed8979014a82c3$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "NormalToAngry_Frame00.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 179, y = 164, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToAngry_Frame01.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 179, y = 110, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToAngry_Frame02.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 179, y = 56, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToAngry_Frame03.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 179, y = 2, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToAngry_Frame04.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 120, y = 164, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToAngry_Frame05.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 120, y = 110, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHappy_Frame00.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 179, y = 164, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHappy_Frame01.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 120, y = 56, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHappy_Frame02.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 120, y = 2, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHappy_Frame03.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 61, y = 164, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHappy_Frame04.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 61, y = 110, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHappy_Frame05.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 61, y = 56, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHungry_Frame00.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 179, y = 164, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHungry_Frame01.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 61, y = 2, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHungry_Frame02.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 52 },
				textureRect = { x = 2, y = 168, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHungry_Frame03.png",
				spriteColorRect = { x = 1, y = 3, width = 57, height = 52 },
				textureRect = { x = 2, y = 114, width = 57, height = 52 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHungry_Frame04.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 54 },
				textureRect = { x = 2, y = 58, width = 57, height = 54 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "NormalToHungry_Frame05.png",
				spriteColorRect = { x = 1, y = 2, width = 57, height = 54 },
				textureRect = { x = 2, y = 2, width = 57, height = 54 },
				spriteSourceSize = { width = 59, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

